spring.application.name=backend-sgai

# ===============================
# CONFIGURAÇÃO DO POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sgai_db
spring.datasource.username=${DB_USERNAME:postgres}
# Adicione o :postgre logo abaixo para servir de valor padrão caso a variável falhe
spring.datasource.password=${DB_PASSWORD:postgre}

# Atualiza as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# CONFIGURAÇÃO DO MQTT (EMQX)
# ===============================
mqtt.broker.url=tcp://broker.emqx.io:1883
mqtt.client.id=SGAI_BACKEND_MASTER